[package]
name = "backend"
version = "0.1.0"
edition = "2024"

[dependencies]
sqlx = { version = "0.8", features = ["runtime-tokio", "sqlite" ] }
actix-web = "4"
serde = {version = "1.0.219", features = ["derive"]}
